config/routes.rb
Resque::Application.routes.draw do
  resources :application_forms
  mount Resque::Server, :at => "/resque"

  

end

app/models/application_form.rb
class ApplicationForm < ActiveRecord::Base
  after_save :push_queue

  def push_queue
    unless self.status_changed?
      Resque.enqueue(ApplicationFormManager, self.id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/application_forms_controller.rb
class ApplicationFormsController < ApplicationController
  before_action :set_application_form, only: [:show, :edit, :update, :destroy]

  # GET /application_forms
  # GET /application_forms.json
  def index
    @application_forms = ApplicationForm.all
  end

  # GET /application_forms/1
  # GET /application_forms/1.json
  def show
  end

  # GET /application_forms/new
  def new
    @application_form = ApplicationForm.new
  end

  # GET /application_forms/1/edit
  def edit
  end

  # POST /application_forms
  # POST /application_forms.json
  def create
    @application_form = ApplicationForm.new(application_form_params)

    respond_to do |format|
      if @application_form.save
        format.html { redirect_to @application_form, notice: 'Application form was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application_form }
      else
        format.html { render action: 'new' }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_forms/1
  # PATCH/PUT /application_forms/1.json
  def update
    respond_to do |format|
      if @application_form.update(application_form_params)
        format.html { redirect_to @application_form, notice: 'Application form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_forms/1
  # DELETE /application_forms/1.json
  def destroy
    @application_form.destroy
    respond_to do |format|
      format.html { redirect_to application_forms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_form
      @application_form = ApplicationForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_form_params
      params.require(:application_form).permit(:name, :status)
    end
end

app/helpers/application_forms_helper.rb
module ApplicationFormsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application_forms/_form.html.erb
<%= form_for(@application_form) do |f| %>
  <% if @application_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application_form.errors.count, "error") %> prohibited this application_form from being saved:</h2>

      <ul>
      <% @application_form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/application_forms/edit.html.erb
<h1>Editing application_form</h1>

<%= render 'form' %>

<%= link_to 'Show', @application_form %> |
<%= link_to 'Back', application_forms_path %>

app/views/application_forms/index.html.erb
<h1>Listing application_forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @application_forms.each do |application_form| %>
      <tr>
        <td><%= application_form.name %></td>
        <td><%= application_form.status %></td>
        <td><%= link_to 'Show', application_form %></td>
        <td><%= link_to 'Edit', edit_application_form_path(application_form) %></td>
        <td><%= link_to 'Destroy', application_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application form', new_application_form_path %>

app/views/application_forms/new.html.erb
<h1>New application_form</h1>

<%= render 'form' %>

<%= link_to 'Back', application_forms_path %>

app/views/application_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application_form.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @application_form.status %>
</p>

<%= link_to 'Edit', edit_application_form_path(@application_form) %> |
<%= link_to 'Back', application_forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resque</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>